studentportal/urls.py
from django.contrib import admin
from django.urls import path, include
from studyportal import views
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('studyportal.urls')),
                  path('register/', views.registerUser, name="register"),
                  path('profile/', views.profile, name="profile"),
                  path('login/', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
                  path('logout/', auth_views.LogoutView.as_view(template_name="logout.html"), name="logout"),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

studyportal/urls.py
from django.urls import path
from studyportal import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name="home"),
    path('home/', views.home, name="home"),
    path('notes/', views.notes, name="notes"),
    path('youtube/', views.youtube, name="youtube"),
    path('todo/', views.todo, name="todo"),
    path('books/', views.books, name="books"),
    path('wiki/', views.wiki, name="wiki"),
    path('dictionary/', views.dictionary, name="dictionary"),

    path('delete_notes/<int:pk>', views.delete_notes, name="delete_notes"),
    path('delete_todo/<int:pk>', views.delete_todo, name="delete_todo"),
    path('update_todo/<int:pk>', views.update_todo, name="update_todo"),


]

studyportal/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Notes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    desc = models.TextField()

    class Meta:
        verbose_name = "notes"
        verbose_name_plural = "notes"

    def __str__(self):
        return self.title


class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    is_finished = models.BooleanField(default=False)

    def __str__(self):
        return self.title

studyportal/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm


class NotesForm(forms.ModelForm):
    class Meta:
        model = Notes
        fields = ['title', 'desc']


class PanelForm(forms.Form):
    text = forms.CharField(max_length=200, label="Enter Something To Search ")


class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ['title', 'is_finished']


class UserRegistration(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <title>Students Learning Panel</title>

    <!-- font-awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"/>

    <!-- styles -->

    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>


    <!--    Other Links-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    {% block css %}

    {% endblock %}

    <style>
    </style>

</head>

<body>
<nav class="navbar-dark " style="background-color: black; margin-top: -5px">
    <div class="nav-center">
        <!-- Nav Header -->
        <div class="nav-header">
            <a class="navbar-brand" href="/home">Learning Panel</a>
            <button class="nav-toggle">
                <i class="fas fa-bars"></i>
            </button>
        </div>
        <!-- links -->

        <ul class="links" style="margin-bottom: 0rem">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/home">Home</a>
            </li>
            {% if user.is_authenticated %}
                <li style="color: white; line-height: 0.5;" class="btn dropdown-toggle" id="dropdownMenuButton"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Options
                </li>
                <div class="dropdown-menu" style="background-color: black">
                    <a class="dropdown-item" href="/books">Books</a>
                    <a class="dropdown-item" href="/wiki">Wikipedia</a>
                    <div style="background-color: white" class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/dictionary">Dictionary</a>
                    <a class="dropdown-item" href="/youtube">Youtube</a>
                    <div style="background-color: white" class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/todo">To-do</a>
                    <a class="dropdown-item" href="/notes">Notes</a>
                    <div style="background-color: white" class="dropdown-divider"></div>
                </div>
                <li class="nav-item">
                    <a class="nav-link" href="/profile">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/logout">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="/register">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/login">Login</a>
                </li>
            {% endif %}
        </ul>
        <!-- social media -->
        <ul class="social-icons" style="margin-bottom: 0rem">
            <li>
                <a href="https://twitter.com/_roshan_rasal_" target="_blank">
                    <i class="fab fa-twitter"></i>
                </a>
            </li>
            <li>
                <a href="https://www.linkedin.com/in/roshan-r-792a79184/" target="_blank">
                    <i class="fab fa-linkedin"></i>
                </a>
            </li>
            <li>
                <a href="https://www.instagram.com/_roshan_rasal_/" target="_blank">
                    <i class="fab fa-instagram"></i>
                </a>
            </li>
        </ul>
    </div>
</nav>

{% block div %}

{% endblock %}

<main style="background-color: black;">

    {% block body %}

    {% endblock %}
</main>
<!-- javascript -->
<script src="{% static "js/main.js" %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
</script>
</body>

</html>

templates/books.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <br>
    {% load crispy_forms_tags %}
    <section class='text-center container'>
        <hr style="background-color: white; opacity: 0.9; height: 1px">
        <h2 style="color: white">Search for your favourite books!</h2>
        <hr style="background-color: white; opacity: 0.9; height: 1px">
        <br><br>
        <form action="" method="post">
            {% csrf_token %}
            <div id="div_id_text" class="form-group">
                <label for="id_text" class=" requiredField" style="color: white">
                    Enter Something To Search <span class="asteriskField">*</span> </label>
                <div class=""><input type="text" name="text" maxlength="200"
                                     class="textinput textInput form-control" required="" id="id_text"></div>
            </div>

            <button href="" class="btn btn-outline-info" type="submit" value="Submit">
                Search
            </button>
        </form>
        <br>

        {% for result in results %}
            <a href="{{ result.preview }}" target="_blank">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-3">
                                <img class="img-fluid" src="{{ result.thumbnail }}" alt="">

                            </div>
                            <div class="col-md-9">
                                <h3 class="p-0 m-0">{{ result.title }}</h3>
                                <b>
                                    <u>
                                        <h5 class="p-0 m-0">{{ result.subtitle }}</h5>
                                    </u>
                                </b>
                                {% if result.description %}
                                    <h6 class="p-0 m-1">{{ result.description }}</h6>
                                {% endif %}
                                <b>
                                    {% if result.categories %}
                                        <h6 class="ml-0 mt-3">Category:
                                            {% for category in result.categories %}
                                                {{ category }}
                                            {% endfor %}
                                        </h6>
                                    {% endif %}
                                    {% if result.count %}
                                        <h6 class="ml-0 mt-1">Pages: {{ result.count }}</h6>
                                    {% endif %}
                                    {% if result.rating %}
                                        <h6 class="ml-0 mt-1">Rating: {{ result.rating }}</h6>
                                    {% endif %}
                                </b>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            <br>
        {% endfor %}
        <br>
    </section>
    <br>
    <div style="text-align: center; color: white"></div>
    <div style="text-align: center; color: white" class="mt-4">© 2022 by Ashoka College Students</div>
    </div><br>

{% endblock %}

templates/dictionary.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <br><br>
    <section class='text-center container'>
        <hr style="background-color: white; opacity: 0.9; height: 1px">
        <h2 style="color: white">Student Dictionary</h2>
        <hr style="background-color: white; opacity: 0.9; height: 1px">
        <i style="color: wheat">Enter any word to get the phonetics, definition and an example for that word</i>
        <br><br>
        <form action="" method="post">
            {% csrf_token %}
            <div id="div_id_text" class="form-group">
                <label for="id_text" class=" requiredField" style="color: white">
                    Enter Something To Search <span class="asteriskField">*</span> </label>
                <div class=""><input type="text" name="text" maxlength="200"
                                     class="textinput textInput form-control" required="" id="id_text"></div>
            </div>
            <button href="" class="btn btn-outline-info" type="submit" value="Submit">
                Search
            </button>
        </form>
        <br>
        <div class="content-section p-0 mt-5">
            {% if input %}
                <div class="custom-header">
                    <h2>{{ input }}</h2>
                    <h6>{{ phonetics }}</h6>
                    <audio id="player" src="{{ audio }}"></audio>
                    <a onclick="document.getElementById('player').play()"><i class='fa fa-volume-up fa-2x'></i>
                    </a>
                </div>
                </div>

                <hr class="p-0 m-0">

                <p class="float-left">
                <h4 style="color: white">Definition: {{ definition }}</h4>
                <h4 style="color: white">Example: {{ example }}</h4>
                </p> <br>
                <a style="color: white; font-size: 20px">
                    Synonyms:
                    {% for synonym in  synonyms %}
                        {{ synonym }}
                    {% endfor %}
                </a>
                <hr>
                </div>
            {% else %}
                <h2>Sorry, API request limit exceeded</h2>
            {% endif %}
    </section>
    <br>
    <div style="text-align: center; color: white"></div>
    <div style="text-align: center; color: white" class="mt-4">© 2022 by Ashoka College Students</div>
    </div><br>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<style>
    body,
    html {
        height: 100%;
        padding: 0;
        margin: 0;

    }

    .bg {
        /* The image used */
        background-image: url("{% static 'img/Home.jpg' %}");
        /* Full height */
        height: 100%;
        margin: 0;
        padding: 0;
        width: 100%;
        /* Center and scale the image nicely */
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }

    @media only screen and (max-width: 480px) {
        .bg {
            width: 800px;
        }
    }

    @media only screen and (max-width: 600px) {
        .navbar-dark {
            margin-bottom: -1px;
        }
    }

    @media only screen and (max-width: 600px) {
        .navbar-dark {
            margin-bottom: 0px;
        }
    }
</style>
{% endblock %}


{% block div %}
<div class="bg"></div>
{% endblock %}

{% block body %}
<br>
<section class="container text-center">
    <hr style="background-color: white; opacity: 0.9; height: 1px">
    <h3 style="color: wheat">Welcome</h3>
    <hr style="background-color: white; opacity: 0.9; height: 1px">
    <br>
    <div class="row">
        <div class="col-md-4">
            <a href="/notes">
                <div class="card">
                    <a href="/notes">
                        <img class="card-img-top" src="{% static 'img/notes.jfif' %}" alt="Notes image">
                    </a>
                    <div class="card-body">
                        <h5 class="card-title ">
                            Notes
                        </h5>
                        Create Notes to refer them later. They are stored permanently until deleted
                    </div>
                </div>
            </a>
        </div>

        <div class="col-md-4">
            <div class="card">
                <a href="/youtube">
                    <img class="card-img-top" src="{% static 'img/utube.jfif' %}" alt="Notes image">
                </a>
                <div class="card-body">
                    <h5 class="card-title ">
                        Youtube
                    </h5>
                    Search Youtube and select your desired video to play it on youtube
                </div>
            </div>
            </a>
        </div>
        <div class="col-md-4">
            <div class="card">
                <a href="/todo">
                    <img class="card-img-top" width="807" height="308" src="{% static 'img/todo.jfif' %}"
                        alt="Notes image">
                </a>
                <div class="card-body">
                    <h5 class="card-title ">
                        To Do
                    </h5>
                    Add your to-do lists for your day and remove them as you finish
                </div>
            </div>
        </div>
    </div>
    <hr style="background-color: white; opacity: 0.9; height: 1px">
    <br><br><br>
    <hr style="background-color: white; opacity: 0.9; height: 1px">
    <div class="row">
        <div class="col-md-4 ">

            <div class="card mt-20">
                <a href="/books">
                    <img class="card-img-top" src="{% static 'img/books.jfif' %}" alt="Notes image">
                </a>
                <div class="card-body">
                    <h5 class="card-title ">
                        Books
                    </h5>
                    Browse books from a list of neatly organised book menu
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <a href="/dictionary">
                    <img class="card-img-top" width="807" height="300" src="{% static 'img/dict.jfif' %}"
                        alt="Notes image">
                </a>
                <div class="card-body">
                    <h5 class="card-title ">
                        Dictionary
                    </h5>
                    Enter any word to find it's meaning along with it's usage!
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <a href="/wiki">
                    <img class="card-img-top" width="807" height="300" src="{% static 'img/Wikipedia-Logo.png' %}"
                        alt="Notes image">
                </a>
                <div class="card-body">
                    <h5 class="card-title ">
                        Wikipedia
                    </h5>
                    Homework and Assignments? Search wikipedia to get fast results
                </div>
            </div>
        </div>
    </div>
    <hr style="background-color: white; opacity: 0.9; height: 1px">
</section>
<br>
<div style="text-align: center; color: white"></div>
<div style="text-align: center; color: white" class="mt-4">© 2022 by Ashoka College Students</div>
</div><br>







{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
    <style>
        @media (min-width: 1400px) {
            .container {
                width: 100%;
                max-width: 500px;
                padding: 15px;
                margin: auto;
                color: white;
            }
        }

        .form-group {
            color: white;
        }

        .text-muted {
            /* --bs-text-opacity: 25; */
            color: #838683 !important;
        }
    </style>
{% endblock %}

{% block body %} <br><br><br><br>

    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <hr style="background-color: white; opacity: 0.9; height: 1px">
                <h3 style="text-align: center">Log In</h3>
                <hr style="background-color: white; opacity: 0.9; height: 1px">
                <br>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button href="" class="btn btn-outline-info" type="submit" style="width: 100%; line-height: 2">
                    Sign In
                </button>
            </div>
        </form>
        <br>
        <div class="border-top pt-3">
        </div>
        <br>
        <div style="text-align: center; color: white">
            Don't have an account? <a href="/register" style="color:blue">Create One</a>
        </div>
        <p style="text-align: center; color: white" class="mt-4">© 2022 by Ashoka College Students</p>
    </div>

{% endblock %}

templates/notes.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<br>

<div class="container">

    <fieldset class="form-group">
        <div style="background-color: white" class="dropdown-divider"></div>
        <legend style="color: white; text-align: center">Create Notes</legend>
        <div style="background-color: white" class="dropdown-divider"></div>
    </fieldset>
    <br>
    {% if messages %}
    {% for message in messages %}
    <div style="text-align: center" class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
    {% endif %}
    <br>
    <div class="row">
        {% for note in notes %}
        <div class="col-md-3">
            <a>
                <div class="card">
                    <div style="color: white" class="card-header">{{ note.title }}</div>
                    <div class="card-body"><b>{{ note.desc |slice:"0:100" }}</b></div>
                    <div class="card-footer mt-auto "><a href="{% url 'delete_notes' note.id %}">
                            <i style="color: red" class="fa fa-trash fa-2x"></i></a>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
        <br><br>

    </div>
</div>
<br><br>
<div class="container">
    <form method="POST">
        {% csrf_token %}

        <div id="div_id_title" class="form-group"><label for="id_title" class=" requiredField" style="color: white">
                Title<span class="asteriskField">*</span> </label>
            <div class=""><input type="text" name="title" maxlength="250" class="textinput textInput form-control"
                    required="" id="id_title"></div>
        </div>
        <div id="div_id_desc" class="form-group"><label for="id_desc" class=" requiredField" style="color: white">
                Description<span class="asteriskField">*</span> </label>
            <div class=""><textarea name="desc" cols="40" rows="10" class="textarea form-control" required=""
                    id="id_desc"></textarea></div>
        </div>

        <div class="form-group">
            <button href="" class="btn btn-outline-info" type="submit">
                Create
            </button>
        </div>
    </form>
</div>
<br>
<div style="text-align: center; color: white"></div>
<div style="text-align: center; color: white" class="mt-4">© 2022 by Ashoka College Students</div>
</div><br>
{% endblock %}

templates/todo.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    {% load crispy_forms_tags %}
    <br><br>

    <div class="container">
        {% if not todos_done %}
            <fieldset class="form-group">
                <div style="background-color: white" class="dropdown-divider"></div>
                <legend style="color: white; text-align: center">Create Todo List</legend>
                <div style="background-color: white" class="dropdown-divider"></div>
            </fieldset>
            <br>
            {% if messages %}
                {% for message in messages %}
                    <div style="text-align: center" class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
            {% endif %}
            <br>

            <table class="table table-striped table-bordered table-hover table-dark">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Status</th>
                    <th scope="col">Delete</th>
                </tr>
                </thead>
                <tbody>
                {% for todo in todos %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ todo.title }}</td>
                        <td>
                            <a href="{% url 'update_todo' todo.id %}">
                                <div class="form-check">
                                    {% if todo.is_finished == True %}
                                        <input class="form-check-input" type="checkbox" value="" checked>
                                    {% else %}
                                        <input class="form-check-input" type="checkbox" value="">
                                    {% endif %}
                                    <label class="form-check-label text-light" for="flexCheckDefault">
                                        Mark as Completed
                                    </label>
                                </div>
                            </a>
                        </td>

                        <td><a href="{% url 'delete_todo' todo.id %}"><i class="fa fa-trash fa-2x"></i></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <br>
            <hr style="background-color: white; opacity: 0.9; height: 1px">
            <h4 style="color: white; text-align: center">All tasks have been done!! create to add more</h4>
            <hr style="background-color: white; opacity: 0.9; height: 1px">
        {% endif %}
    </div><br><br>
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <div id="div_id_title" class="form-group">
                <label for="id_title" class=" requiredField" style="color: white">
                    Title<span class="asteriskField">*</span>
                </label>
                <div class=""><input type="text" name="title" maxlength="250" class="textinput textInput form-control"
                                     required="" id="id_title"></div>
            </div>
            <div class="form-group">
                <div id="div_id_is_finished" class="form-check">
                    <input type="checkbox" name="is_finished" class="checkboxinput form-check-input"
                           id="id_is_finished">
                    <label style="color: white" for="id_is_finished" class="form-check-label">
                        Is finished
                    </label></div>
            </div>

            <div class="form-group">
                <button href="" class="btn btn-outline-info" type="submit">
                    Create
                </button>
            </div>
        </form>
    </div>
    <br>
    <div style="text-align: center; color: white"></div>
    <div style="text-align: center; color: white" class="mt-4">© 2022 by Ashoka College Students</div>
    </div><br>
{% endblock %}

templates/wiki.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <br><br>
    <section class='text-center container'>
        <hr style="background-color: white; opacity: 0.9; height: 1px">
        <h2 style="color: white">Search articles in wikipedia</h2>
        <hr style="background-color: white; opacity: 0.9; height: 1px">
        <br>
        <form action="" method="post">
            {% csrf_token %}
            <div id="div_id_text" class="form-group">
                <label for="id_text" class=" requiredField" style="color: white">
                    Enter Something To Search <span class="asteriskField">*</span> </label>
                <div class=""><input type="text" name="text" maxlength="200"
                                     class="textinput textInput form-control" required="" id="id_text"></div>
            </div>
            <button href="" class="btn btn-outline-info" type="submit" value="Submit">
                Search
            </button>
        </form>
        <br>
        <div class="container">
            <div class="content-section p-0 mt-5">
                <a href="" class="p-0 m-0" target="_blank">
                    <div class="custom-header">
                        <h2>{{ title }}</h2>{{ title }}
                        <h6>{{ link }}</h6>
                    </div>
                </a>

                <hr class="p-0 m-0">
                <p class="description m-5 p-5">
                    {{ details }}
                </p>
                <hr>
            </div>
        </div>
    </section>
    <br>
    <div style="text-align: center; color: white"></div>
    <div style="text-align: center; color: white" class="mt-4">© 2022 by Ashoka College Students</div>
    </div><br>

{% endblock %}

templates/youtube.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <br>
    {% load crispy_forms_tags %}
    <section class='text-center container'>
        <hr style="background-color: white; opacity: 0.9; height: 1px">
        <h2 style="color: white">Search Videos in Youtube</h2>
        <hr style="background-color: white; opacity: 0.9; height: 1px">
        <br><br>
        <form action="" method="post">
            {% csrf_token %}
            <div id="div_id_text" class="form-group">
                <label for="id_text" class=" requiredField" style="color: white">
                    Enter Something To Search <span class="asteriskField">*</span> </label>
                <div class=""><input type="text" name="text" maxlength="200"
                                     class="textinput textInput form-control" required="" id="id_text"></div>
            </div>

            <button href="" class="btn btn-outline-info" type="submit" value="Submit">
                Search
            </button>
        </form>
        <br>

        {% for result in results %}
            <a href="{{ result.link }}" target="_blank">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-5">
                                <img class="img-fluid" src="{{ result.thumbnail }}" alt="">

                            </div>
                            <div class="col-md-7">
                                <h3 class="p-0 m-0">{{ result.title }}</h3>
                                <b>
                                    <u>
                                        <h5 class="p-0 m-0">{{ result.channel }}</h5>
                                    </u>
                                </b>
                                <h6 class="p-0 m-1">{{ result.description }}</h6>
                                <b>
                                    <h6 class="ml-0 mt-3">{{ result.duration }}</h6>
                                    <h6 class="ml-0 mt-1">{{ result.views }}</h6>
                                    <h6 class="ml-0 mt-1">{{ result.published }}</h6>
                                </b>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            <br>
        {% endfor %}
        <br>
    </section>
    <br>
    <div style="text-align: center; color: white"></div>
    <div style="text-align: center; color: white" class="mt-4">© 2022 by Ashoka College Students</div>
    </div><br>

{% endblock %}